### ISSUE TITLE
Implement Packing Functionality for .fdata Files

### ISSUE THREAD

**Issue by Digote** [DeathChaos25/fdata_dump#1]
Hello, congratulations on the tool; it works perfectly in the test I am conducting with the game **Fate/Samurai Remnant**.
I'm not sure if it's in your plans, but would it be difficult to implement the feature to repackage the .fdata file?
I am looking to translate the game Fate/Samurai Remnant. I have managed to understand the logic of the text container, but I need to change the game's font because it lacks some accents for my language.

Thank you very much for the tool.

**Comment by elior316** [comment]
hello' my name is elior, I tried to download and use your fdata extract tool but when I click on"fdata_dump.exe" nothing happens, can you please tell me what to do?I try to dump the new fate samurai 3d models game but It's doesn't work
thanks elior316

**Comment by elior316** [comment]
how did you use it?
![image](https://github.com/DeathChaos25/fdata_dump/assets/164087549/443fd928-8b0f-4640-8eef-c83f8acf336b)

**Comment by elior316** [comment]
If I click on the fdata_dump nothing happaned

**Comment by elior316** [comment]
> Hello, congratulations on the tool; it works perfectly in the test I am conducting with the game **Fate/Samurai Remnant**. I'm not sure if it's in your plans, but would it be difficult to implement the feature to repackage the .fdata file? I am looking to translate the game Fate/Samurai Remnant. I have managed to understand the logic of the text container, but I need to change the game's font because it lacks some accents for my language.
> 
> Thank you very much for the tool.

how did you did it with the fate game? please help me
